# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:

      MONGODB_URI: mongodb://localhost:27017/dotcot # spin up local instance for GH Actions tests
      FRONTEND_URL: http://localhost:${process.env.PORT}
      REACT_APP_BACKEND_URL: http://localhost:${process.env.PORT}/
      REACT_APP_FRONTEND_URL: http://localhost:${process.env.PORT}

      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      FACEBOOK_APP_ID: ${{secrets.FACEBOOK_APP_ID}}
      FACEBOOK_APP_SECRET: ${{secrets.FACEBOOK_APP_SECRET}}
      FACEBOOK_TEST_APP_ID: ${{secrets.FACEBOOK_TEST_APP_ID}}
      FACEBOOK_TEST_APP_SECRET: ${{secrets.FACEBOOK_TEST_APP_SECRET}}
      LINKEDIN_CLIENT_ID: ${{secrets.LINKEDIN_CLIENT_ID}}
      LINKEDIN_CLIENT_SECRET: ${{secrets.LINKEDIN_CLIENT_SECRET}}
      DOTCOT_SECRET: 'secret-key'
      

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['4.2', '4.4']


    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - run: npm run install-all
    - run: CI=true npm run test
    - run: CI=false npm run static-build
